"""Shared provenance labels used by every analytical and circuit module."""

from enum import Enum


class Evidence(str, Enum):
    P24_EXPLICIT = "P24_EXPLICIT"
    P24_DERIVED = "P24_DERIVED"
    P25_SUPPLEMENT = "P25_SUPPLEMENT"
    CROSS_PAPER_EXTENSION = "CROSS_PAPER_EXTENSION"
    EXTERNAL_DEVICE_DATA = "EXTERNAL_DEVICE_DATA"
    EXPLORATORY_ASSUMPTION = "EXPLORATORY_ASSUMPTION"
    MODEL_CALIBRATION = "MODEL_CALIBRATION"
    PROJECT_DECISION = "PROJECT_DECISION"
    UNKNOWN_BLOCKING = "UNKNOWN_BLOCKING"
