"""Generate scb_multi.v (C2): M scb_ctrl instances, instance 0 the master (SLAVE = 0), 1..M-1 slaves (SLAVE = 1).
Every scb_ctrl port except clk and rst becomes a top port M times as wide; instance m uses slice m. Run after any
change to scb_ctrl's ports:

    python3 src/scb_ivr/cosim/rtl/gen_multi.py
"""
from __future__ import annotations

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
PARAMS = ("N", "TW", "FB", "CW", "AW", "KW", "KPW", "FRAC")
DEFAULTS = {"N": 4, "TW": 32, "FB": 5, "CW": 8, "AW": 12, "KW": 16, "KPW": 24, "FRAC": 16}
SHARED = ("clk", "rst")


def ports(src: str):
    body = src[src.index(") (") + 3: src.index(");", src.index(") ("))]
    out = []
    for line in body.splitlines():
        m = re.match(r"\s*(input|output)\s+(?:wire|reg)\s*(\[[^\]]+\])?\s*(\w+)\s*,?", line)
        if not m:
            continue
        direction, rng, name = m.groups()
        if rng is None:
            width = "1"
        else:
            hi = rng[1:-1].split(":")[0].strip()
            mm = re.fullmatch(r"(.+)-1", hi)
            width = f"({mm.group(1)})" if mm else str(int(hi) + 1)
        out.append((direction, width, name))
    return out


def generate() -> str:
    src = (HERE / "scb_ctrl.v").read_text()
    ps = ports(src)
    head = ["`timescale 1ns / 1ps",
            "// GENERATED by gen_multi.py from scb_ctrl.v's ports - do not edit.",
            "// M scb_ctrl modules: instance 0 the master (SLAVE = 0), instances 1..M-1 slaves (SLAVE = 1, C2). Every port",
            "// except clk and rst is M times as wide; instance m uses slice m.",
            "module scb_multi #(",
            "    parameter M = 2,"]
    head += [f"    parameter {k} = {DEFAULTS[k]}," for k in PARAMS[:-1]] + [f"    parameter {PARAMS[-1]} = {DEFAULTS[PARAMS[-1]]}", ") ("]
    decl = []
    for d, w, n in ps:
        if n in SHARED:
            decl.append(f"    {d} wire {n}")
        else:
            decl.append(f"    {d} wire [M*{w}-1:0] {n}")
    lines = head + [",\n".join(decl), ");", "    genvar m;", "    generate", "        for (m = 0; m < M; m = m + 1) begin : g_mod",
                    "            scb_ctrl #(" + ", ".join(f".{k}({k})" for k in PARAMS) + ", .SLAVE(m > 0 ? 1 : 0)) u_ctrl ("]
    conns = []
    for d, w, n in ps:
        conns.append(f"                .{n}({n})" if n in SHARED else f"                .{n}({n}[m*{w} +: {w}])")
    lines += [",\n".join(conns), "            );", "        end", "    endgenerate", "endmodule", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    (HERE / "scb_multi.v").write_text(generate())
    print("wrote", HERE / "scb_multi.v")
